<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find vss_simulation)/urdf/common_properties.urdf.xacro" />
  <xacro:include filename="$(find vss_simulation)/urdf/inertias.urdf.xacro" />
  <xacro:include filename="$(find vss_simulation)/urdf/roda_boba.urdf.xacro" />
  <xacro:include filename="$(find vss_simulation)/urdf/wheel.urdf.xacro"/>

  <xacro:macro name="vss_base_macro" params="prefix mass size_x size_y size_z wheel_mass wheel_width wheel_radius wheel_center_height">
    <link name="${prefix}base_link">
      <visual>
        <origin xyz="0 0 ${wheel_radius-wheel_center_height+size_z/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${size_x} ${size_y} ${size_z}"/>
        </geometry>
        <material name="blue"/>
      </visual>

      <collision>
        <origin xyz="0 0 ${wheel_radius-wheel_center_height+size_z/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${size_x} ${size_y} ${size_z}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 ${wheel_radius-wheel_center_height+size_z/2}" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <xacro:cuboid_inertia_macro mass="${mass}" width="${size_y}" length="${size_x}" height="${size_z}"/>
      </inertial>
      
      <gazebo>
        <material>Gazebo/Blue</material>
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
      </gazebo>
    </link>

    <xacro:vss_wheel_macro
      prefix="${prefix}R_"
      parent="${prefix}base_link" 
      base_size_x="${base_size_x}"
      reflect = "1"
      mass="${wheel_mass}"
      width="${wheel_width}"
      radius="${wheel_radius}"
      absolute_center_height="${wheel_radius}"
    />
    <xacro:vss_wheel_macro
      prefix="${prefix}L_"
      parent="${prefix}base_link" 
      base_size_x="${base_size_x}"
      reflect = "-1"
      mass="${wheel_mass}"
      width="${wheel_width}"
      radius="${wheel_radius}"
      absolute_center_height="${wheel_radius}"
    />

    <xacro:roda_boba_macro 
    prefix="${prefix}front_"
    parent="${prefix}base_link" 
    x_offset="0" 
    y_offset="${pos_y_roda_boba}" 
    z_offset="${pos_z_roda_boba}"
    />

    <xacro:roda_boba_macro 
    prefix="${prefix}rear_"
    parent="${prefix}base_link" 
    x_offset="0" 
    y_offset="${-pos_y_roda_boba}" 
    z_offset="${pos_z_roda_boba}"
    />
    
  </xacro:macro>
</robot>