/**/controller_manager:
  ros__parameters:
    update_rate: 100
    robot_description: /**/robot_description
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController
  
/**/diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: '**_base_link'

    left_wheel_names: ['**_L_wheel_to_base_joint']
    right_wheel_names: ['**_R_wheel_to_base_joint']
    wheel_separation: 0.065
    wheel_radius: 0.02

    use_stamped_vel: false