robot_team1_center/controller_manager:
  ros__prameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

robot_team1_center/diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: robot_team1_center_base_link

    left_wheel_names: ['robot_team1_center_L_wheel_link']
    right_wheel_names: ['robot_team1_center_R_wheel_link']
    wheel_separation: 0.065
    wheel_radius: 0.02

    use_stamped_vel: false
